set nocompatible
set t_Co=256
set hidden
set encoding=UTF-8
set clipboard^=unnamed,unnamedplus

set textwidth=120
set linebreak
set breakindent
set breakindentopt+=shift:-2
set showbreak=├\ 
set listchars=tab:│\ ,nbsp:▓,trail:░,eol:$,precedes:<,extends:>

set smartindent
set shiftwidth=2
set tabstop=2
set softtabstop=2
set smarttab
set noexpandtab

set number relativenumber
set showmatch
set showcmd
set signcolumn=yes

set wildmenu
set wildmode=longest:full,full
set completeopt+=noinsert,menuone,preview

set splitbelow
set splitright

set foldmethod=syntax
set nofoldenable
set foldlevel=1
set viewoptions+=localoptions

set complete+=k

set undofile

set mouse=a
augroup NO_CURSOR_MOVE_ON_FOCUS
	au!
	au FocusLost * let g:oldmouse=&mouse | set mouse=
	au FocusGained * if exists('g:oldmouse') | let &mouse=g:oldmouse | unlet g:oldmouse | endif
augroup END

filetype plugin indent on
syntax on

highlight clear SpellBad
highlight SpellBad cterm=underline ctermfg=red
highlight clear SpellCap
highlight SpellCap cterm=underline ctermfg=red
highlight clear SpellRare
highlight SpellRare cterm=underline ctermfg=green
highlight clear SpellLocal
highlight SpellLocal cterm=underline ctermfg=blue
highlight Pmenu ctermbg=gray

" navigate windows from any mode
tnoremap <C-h> <C-\><C-N><C-w>h
tnoremap <C-j> <C-\><C-N><C-w>j
tnoremap <C-k> <C-\><C-N><C-w>k
tnoremap <C-l> <C-\><C-N><C-w>l
inoremap <C-h> <C-\><C-N><C-w>h
inoremap <C-j> <C-\><C-N><C-w>j
inoremap <C-k> <C-\><C-N><C-w>k
inoremap <C-l> <C-\><C-N><C-w>l
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
tnoremap <C-left>  <C-\><C-N><C-w>h
tnoremap <C-down>  <C-\><C-N><C-w>j
tnoremap <C-up>    <C-\><C-N><C-w>k
tnoremap <C-right> <C-\><C-N><C-w>l
inoremap <C-left>  <C-\><C-N><C-w>h
inoremap <C-down>  <C-\><C-N><C-w>j
inoremap <C-up>    <C-\><C-N><C-w>k
inoremap <C-right> <C-\><C-N><C-w>l
nnoremap <C-left>  <C-w>h
nnoremap <C-down>  <C-w>j
nnoremap <C-up>    <C-w>k
nnoremap <C-right> <C-w>l

" terminal
tnoremap <Esc> <C-\><C-n>
nnoremap <C-\> :vertical terminal<CR>
tnoremap <C-\> exit<CR>

" miscellaneous
nnoremap gb :ls<CR>:b 
nnoremap <C-space> :set list! list?<CR>
nnoremap <F5> :w<CR>:!%:p<CR>
nnoremap <C-s> :setlocal spell!<CR>
inoremap <c-space> <c-n>
" https://stackoverflow.com/a/1037182
nnoremap <silent> <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

" file explorer
let g:netrw_liststyle = 3
let g:netrw_banner = 0
map <C-E> :Lexplore<CR>

augroup auto_save_view
	autocmd!
	autocmd BufWinLeave * set spellfile& " needed for spellcheck to work with view
	autocmd BufWinLeave * silent! mkview
	autocmd BufWinEnter * silent! loadview
augroup END

autocmd BufNewFile,BufRead *.ino set filetype=arduino
autocmd BufNewFile,BufRead docker-compose.{yaml,yml} set filetype=docker-compose
autocmd BufRead,BufNewFile *.md set filetype=markdown

autocmd FileType tex,plaintex,gitcommit,markdown setlocal spell
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType python compiler pylint
autocmd FileType python nnoremap <buffer> <F4> :w<CR>:make %<CR>
autocmd FileType tex,plaintex nnoremap <F4> :w<CR>:VimtexCompile<CR>
autocmd FileType dockerfile nnoremap <buffer> <F4> :wa<CR>:!docker build -t build . && docker run --rm -it $(docker build -q .)<CR>
autocmd FileType docker-compose nnoremap <buffer> <F4> :wa<CR>:!docker-compose down; docker-compose up -d<CR>
autocmd FileType arduino nnoremap <buffer> <F4> :wa<CR>:!arduino -v --upload %<CR>

" https://vim.fandom.com/wiki/Automatically_open_the_quickfix_window_on_:make
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

let g:indentLine_char = '│'

packadd termdebug
let g:termdebug_wide = 1

let g:airline#extensions#tabline#enabled = 1
let g:airline_symbols_ascii = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'

let g:vimtex_view_method = 'zathura'

set rtp+=/usr/bin/fzf

" These lines must be at the very end of the vimrc file.
" packloadall breaks nvim plugin loading
" packloadall
silent! helptags ALL
