set nocompatible
set t_Co=256
set hidden
set encoding=UTF-8
set clipboard^=unnamed,unnamedplus
set completeopt+=noinsert

set autoindent
set smartindent
set shiftwidth=2
set tabstop=2
set softtabstop=2
set smarttab
set textwidth=120

filetype plugin indent on
syntax on

set number relativenumber
set showmatch
set showcmd

set wildmenu
set wildmode=longest:full,full

set splitbelow
set splitright

set foldmethod=syntax
set nofoldenable
set foldlevel=1

set mouse=a
augroup NO_CURSOR_MOVE_ON_FOCUS
  au!
  au FocusLost * let g:oldmouse=&mouse | set mouse=
  au FocusGained * if exists('g:oldmouse') | let &mouse=g:oldmouse | unlet g:oldmouse | endif
augroup END

set listchars=tab:\|\ ,trail:~,extends:>,precedes:<

map <C-h>     <C-w>h
map <C-j>     <C-w>j
map <C-k>     <C-w>k
map <C-l>     <C-w>
map <C-left>  <C-w><left>
map <C-down>  <C-w><down>
map <C-up>    <C-w><up>
map <C-right> <C-w><right>

nnoremap <silent> <CR> :noh<CR><CR>
nnoremap gb :ls<CR>:b
nnoremap <C-@> :set list! list?<CR>
nnoremap <F5> :wa<CR>:make<CR>
tnoremap <Esc> <C-\><C-n>

augroup auto_save_folds
	autocmd!
  autocmd BufWinLeave * silent! mkview
  autocmd BufWinEnter * silent! loadview
augroup END

autocmd BufNewFile,BufRead *.ino set filetype=arduino
autocmd BufNewFile,BufRead docker-compose.{yaml,yml} set filetype=docker-compose
autocmd BufNewFile,BufRead *.{yaml,yml} set filetype=yaml

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
autocmd FileType python nnoremap <buffer> <F5> :wa<CR>:!python %<CR>
autocmd FileType dockerfile nnoremap <buffer> <F5> :wa<CR>:!docker build -t build . && docker run --rm -it $(docker build -q .)<CR>
autocmd FileType docker-compose nnoremap <buffer> <F5> :wa<CR>:!docker-compose down; docker-compose up -d<CR>
autocmd FileType arduino nnoremap <buffer> <F5> :wa<CR>:!arduino -v --upload %<CR>

let g:netrw_liststyle = 3
let g:netrw_banner = 0

packadd termdebug
let g:termdebug_wide = 1

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

let g:vimtex_view_method = 'mupdf'

set rtp+=/usr/bin/fzf

" These lines must be at the very end of the vimrc file.
packloadall
silent! helptags ALL
