#!/usr/bin/env bash

metric="${METRIC:-read}"
interval="${INTERVAL:-0.1}"
color="#$(xrdb -query | grep "*color8:" | cut -f 2 | cut -c2- | tr '[:lower:]' '[:upper:]')"

if [ $metric = "read" ]
then
	index=6
elif [ $metric = "write" ]
then
	index=7
fi

while true
do
	current=$(iostat -d | grep sda | awk -v i=$index '{ print $i; }')
	instant=$((current-old))
	old=$current

	options=$(printf '"full_text":"%s"' $glyph)
	if [ $instant -eq 0 ]
	then
		options=$(printf '%s,"color":"%s"' $options $color)
	fi

	printf '{%s}\n' $options

	sleep $interval
done
