#!/usr/bin/env perl
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
# Copyright 2014 Benjamin Chretien <chretien at lirmm dot fr>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;
use utf8;
use Getopt::Long;

binmode(STDOUT, ":utf8");

# default values
my $t_freezing	= $ENV{T_FREEZING} || 0;
my $t_cold			= $ENV{T_COLD} || 10;
my $t_warm			= $ENV{T_WARM} || 70;
my $t_hot				= $ENV{T_HOT} || 90;
my $chip				= $ENV{SENSOR_CHIP} || "";
my $temperature = -9999;

sub help {
    print "Usage: temperature [-f <freezing>] [-c <cold>] [-w <warm>] [-h <hot>] [--chip <chip>]\n";
    print "-f <percent>: freezing threshold\n";
    print "-c <percent>: cold threshold\n";
    print "-w <percent>: warm threshold\n";
    print "-h <percent>: hot threshold\n";
    print "--chip <chip>: sensor chip\n";
    exit 0;
}

GetOptions("help|h" => \&help,
           "f=i"    => \$t_freezing,
           "c=i"    => \$t_cold,
           "w=i"    => \$t_warm,
           "h=i"    => \$t_hot,
           "chip=s" => \$chip);

# Get chip temperature
open (SENSORS, "sensors -u $chip |") or die;
while (<SENSORS>) {
    if (/^\s+temp1_input:\s+[\+]*([\-]*\d+\.\d)/) {
        $temperature = $1;
        last;
    }
}
close(SENSORS);

$temperature eq -9999 and die 'Cannot find temperature';

my $step = ($t_warm - $t_cold) / 3;
my $color = "";
my $label = "";

if ($temperature >= $t_hot) {
    $color = "#FF0000";
		$label="";
} elsif ($temperature >= $t_warm) {
    $color = "#FFFF00";
		$label="";
} elsif ($temperature <= $t_freezing) {
    $color = "#0000FF";
		$label="";
} elsif ($temperature <= $t_cold) {
    $color = "#00FFFF";
		$label="";
} elsif ($temperature < $t_cold + $step) {
		$label="";
} elsif ($temperature < $t_cold + (2 * $step)) {
		$label="";
} elsif ($temperature < $t_warm) {
		$label="";
}

# Print short_text, full_text
print "$label $temperature°C\n" x2;

# Print color, if needed
if ($color ne "") {
		print "$color\n";
}

if (($temperature >= $t_hot) || ($temperature <= $t_freezing)) {
	exit 33;
}
exit 0;
